/** Every capability the UI can gate on. */
export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_KPI: 'VIEW_KPI',
  VIEW_PRODUCTIVITY: 'VIEW_PRODUCTIVITY',
  VIEW_SALES: 'VIEW_SALES',
  VIEW_FORECAST: 'VIEW_FORECAST',
  VIEW_SALES_TARGET: 'VIEW_SALES_TARGET',
  VIEW_SCHEDULE: 'VIEW_SCHEDULE',
  GENERATE_SCHEDULE: 'GENERATE_SCHEDULE',
  REVIEW_SCHEDULE_ANOMALY: 'REVIEW_SCHEDULE_ANOMALY',
  ENTER_DAILY_SALES: 'ENTER_DAILY_SALES',
  MANAGE_SALES_TARGET: 'MANAGE_SALES_TARGET',
  MANAGE_STORE: 'MANAGE_STORE',
  MANAGE_STAFF: 'MANAGE_STAFF',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  // The chain-wide Sales -> Labour Hours guideline. Separate from the per-store labour
  // permissions: it sets how many hours EVERY store may use, so a Store Manager sees nothing of
  // it and an Area Coach may read but not change it.
  VIEW_LABOR_GUIDELINE: 'VIEW_LABOR_GUIDELINE',
  MANAGE_LABOR_GUIDELINE: 'MANAGE_LABOR_GUIDELINE',
  IMPORT_FILES: 'IMPORT_FILES',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
  VIEW_ALL_STORES: 'VIEW_ALL_STORES',
  VIEW_AREA_STORES: 'VIEW_AREA_STORES',
  VIEW_OWN_STORE: 'VIEW_OWN_STORE'
};
